# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e2b46c72cc0a02ed10b61d1e95147423948e4cc6813e4545d2e166b1725298981a6bdec599ed0241e81586f28dd70c2151c8bd441f3f91a070da5780a7582e5

test:
  secret_key_base: 39abfbf646fb3e382d1c41f253bce30441f2678448ebf3ef1af8691e1f651ae80c0f306699a9ec87c22b567679af53b4e8297f77f85de79a45189728c833e92d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
